### ISSUE TITLE
ERR_IPC_CHANNEL_CLOSED error

### ISSUE THREAD

**Issue by pronebird** [gilamran/tsc-watch#54]
Hi,

I observe the `ERR_IPC_CHANNEL_CLOSED` error happening from time to time, which abruptly quits my watch script leaving all spawned child processes active. (using `tsc-watch v2.1.1`)

Do you have any ideas to why that may be happening?

```
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:644:16)
    at Object.Signal.send.process.send.function.e [as send] (~/app/node_modules/tsc-watch/lib/tsc-watch.js:77:64)
    at Object.emitSuccess (~/app/node_modules/tsc-watch/lib/tsc-watch.js:80:12)
    at killProcesses.then (~/app/node_modules/tsc-watch/lib/tsc-watch.js:64:16)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

That's my watch script:
https://github.com/mullvad/mullvadvpn-app/blob/master/gui/packages/desktop/scripts/serve.js

**Comment by gilamran** [comment]
Does this happen on the older version of `tsc-watch`?
Can you provide a simple example to reproduce this issue?
Platform?

**Comment by pronebird** [comment]
Running macOS and zsh. I'd have to test if that happens with the older version. Investigating.

**Comment by pronebird** [comment]
I apologise for the false alarm. The log order in my terminal was reversed for some reason, but the chain of events was very much the other way around, so it was my script triggering this by calling `process.exit()` by mistake.
