### ISSUE TITLE
tsc-watch does not quit on CTRL+C

### ISSUE THREAD

**Issue by pronebird** [gilamran/tsc-watch#66]
`tsc-watch` does not seem to properly quit on ctrl+c. then at some point if I change some file, it randomly prints stuff like this to console:

```
----------------------
1:16:00 PM - File change detected. Starting incremental compilation...
1:16:00 PM - Found 0 errors. Watching for file changes.
Error [ERR_IPC_CHANNEL_CLOSED]: Channel closed
    at process.target.send (internal/child_process.js:678:16)
    at Object.Signal.send (~/gui/node_modules/tsc-watch/lib/tsc-watch.js:81:64)
    at Object.emitSuccess (~/gui/node_modules/tsc-watch/lib/tsc-watch.js:84:12)
    at ~/gui/node_modules/tsc-watch/lib/tsc-watch.js:68:16
    at processTicksAndRejections (internal/process/task_queues.js:89:5)

```

Running `tsc-watch` programmatically by creating an instance of `TscWatchClient`.

You think I need to kill it manually on `exit`? i.e:

```
process.on('SIGINT', () => {
  watch.kill();
  process.exit();
});
```

**Comment by pronebird** [comment]
Ah that seems to be the case, had to add a `SIGINT` and `exit` handlers to make sure that the process properly cleans up before quitting.
