### ISSUE TITLE
Running from yarn fails

### ISSUE THREAD

**Issue by fritzblue** [gilamran/tsc-watch#79]
Experimenting with yarn a bit, on the latest stable version of node and the latest RC for `yarn@berry` as of writing:

```
❯ node -v
v12.16.1

❯ yarn -v
2.0.0-rc.29
```

Running `tsc-watch` with any args fails while attempting to spawn a process:

```
❯ yarn run tsc-watch --help

internal/child_process.js:407
    throw errnoException(err, 'spawn');
    ^

Error: spawn ENOTDIR
    at ChildProcess.spawn (internal/child_process.js:407:11)
    at Object.spawn (child_process.js:548:9)
    at spawn (.../.yarn/cache/cross-spawn-npm-5.1.0-a3e220603e-2.zip/node_modules/cross-spawn/index.js:17:18)
    at Object.<anonymous> (.../.yarn/$$virtual/tsc-watch-virtual-5d30396a02/0/cache/tsc-watch-npm-4.1.0-030e21986c-2.zip/node_modules/tsc-watch/lib/tsc-watch.js:48:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.module_1.Module._load (.../.pnp.js:14659:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18) {
  errno: 'ENOTDIR',
  code: 'ENOTDIR',
  syscall: 'spawn'
}
```

Installing via `npm i -D` and running via `npx tsc-watch --help` work as expected, so only the yarn compatibility appears to be broken.

**Comment by gilamran** [comment]
I tried `yarn@berry`, and I don't see `node_modules` after installing `tsc-watch`... Do you know what's all about?

**Comment by gilamran** [comment]
Installing `tsc-watch` with older version of `yarn` will create the `node_modules` folder, and then moving the the new version of `yarn` will work...
Looks like `yarn` changed the way we work with `node_modules` in version 2... Not sure

**Comment by gilamran** [comment]
Is this still an issue?

**Comment by brokenmass** [comment]
@gilamran : yes it is. 

yarn v2 use pnp by default so the node_modules folder does not exist anymore.

Why is the project trying to access the node_modules folder directly ?

**Comment by gilamran** [comment]
It's the `cross-spawn` library that is trying to access the `node_modules` folder.
I did another try (On Windows) with yarn 2, and I don't see this issue anymore.
Do you guys still get the same error?
